"""Add indexes for abi_compatability queries

Revision ID: 6ce8fb9b3329
Revises: bb26306538f0
Create Date: 2020-01-30 16:16:42.100165+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce8fb9b3329'
down_revision = 'bb26306538f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_log_analyzer_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('build_log_analyzer_name', sa.Text(), nullable=True),
    sa.Column('build_log_analyzer_version', sa.Text(), nullable=True),
    sa.Column('build_log_analysis_document_id', sa.Text(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('debug', sa.Boolean(), nullable=False),
    sa.Column('build_log_analyzer_error_reason', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('input_python_package_version_entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['input_python_package_version_entity_id'], ['python_package_version_entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('os_id_idx', 'package_extract_run', ['os_id'], unique=False)
    op.create_index('os_version_id_idx', 'package_extract_run', ['os_id'], unique=False)
    op.create_index('id_idx', 'python_package_version_entity', ['id'], unique=True)
    op.create_index('python_artifact_id_idx', 'requires_symbol', ['python_artifact_id'], unique=False)
    op.create_index('id_idx', 'versioned_symbol', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_idx', table_name='versioned_symbol')
    op.drop_index('python_artifact_id_idx', table_name='requires_symbol')
    op.drop_index('id_idx', table_name='python_package_version_entity')
    op.drop_index('os_version_id_idx', table_name='package_extract_run')
    op.drop_index('os_id_idx', table_name='package_extract_run')
    op.drop_table('build_log_analyzer_run')
    # ### end Alembic commands ###
