"""Added new table python_package_license

Revision ID: 737977503120
Revises: aba59a2fec95
Create Date: 2021-10-26 16:49:44.021807+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "737977503120"
down_revision = "aba59a2fec95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "python_package_license",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("license_name", sa.Text(), nullable=False),
        sa.Column("license_identifier", sa.Text(), nullable=False),
        sa.Column("license_version", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "python_package_version_entity_rule", type_="unique")
    op.drop_constraint(None, "python_package_version", type_="foreignkey")
    op.drop_column("python_package_version", "package_license_id")
    op.drop_table("python_package_license")
    # ### end Alembic commands ###
