"""Added Kebechet Installation Table.

Revision ID: 77b74d7f0f85
Revises: a7442899ef28
Create Date: 2020-05-14 21:16:29.635409+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b74d7f0f85'
down_revision = 'a7442899ef28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kebechet_github_installations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('repo_name', sa.Text(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('installation_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kebechet_github_installations')
    # ### end Alembic commands ###
