"""Migrate license solver data

Revision ID: 7f7411e247d6
Revises: 2a4632197512
Create Date: 2022-09-19 12:26:03.463149+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f7411e247d6"
down_revision = "2a4632197512"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "python_package_license", ["license_name", "license_identifier", "license_version"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "python_package_license", type_="unique")
    # ### end Alembic commands ###
