"""rename thoth s2i columns

Revision ID: 930b47e27b6c
Revises: b718c0f8bc53
Create Date: 2022-01-19 16:56:54.439445+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930b47e27b6c'
down_revision = 'b718c0f8bc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('has_symbol', 'software_environment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('has_symbol', 'versioned_symbol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'python_package_version_entity_rule', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'python_package_version_entity_rule', type_='unique')
    op.alter_column('has_symbol', 'versioned_symbol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('has_symbol', 'software_environment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
