"""Changed kebechet table columns to non nullable

Revision ID: b6e6f44774cf
Revises: 77b74d7f0f85
Create Date: 2020-05-18 17:22:59.915586+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e6f44774cf'
down_revision = '77b74d7f0f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kebechet_github_installations', 'installation_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('kebechet_github_installations', 'private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('kebechet_github_installations', 'repo_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kebechet_github_installations', 'repo_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('kebechet_github_installations', 'private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('kebechet_github_installations', 'installation_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
