"""Relax constraint on inspection number to allow DM to sync correctly

Revision ID: e61a129ae25c
Revises: 342d45db2dc2
Create Date: 2020-11-06 08:18:34.792960+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61a129ae25c'
down_revision = '342d45db2dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection_run', 'inspection_result_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection_run', 'inspection_result_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
