- project:
    check:
      jobs:
        - pipenv
        - run-test-command:
            vars:
              test_command:
                - "pipenv run python3 setup.py test"
        - linters:
            vars:
              linters:
                - coala
    gate:
      queue: core
      jobs:
        - linters:
            vars:
              linters:
                - coala

    release:
      jobs:
        - upload-pypi-sesheta
