- project:
    check:
      queue: thoth-station/core
      jobs:
        - thoth-coala
        - thoth-pytest
    gate:
      queue: thoth-station/core
      jobs:
        - thoth-coala
    release:
      jobs:
        - upload-pypi-sesheta
    post:
      jobs:
        - trigger-build:
            vars:
              webhook_url: https://paas.upshift.redhat.com/oapi/v1/namespaces/thoth-test-core/buildconfigs/user-api/
    kebechet-auto-gate:
      queue: thoth-station/core
      jobs:
        - thoth-coala
